spring:
  application:
    name: api-gateway-zuul

server:
  port: 8765

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    app-one:
      service-id: app-one
      path: /app-one/**
    app-two:
      service-id: app-two
      path: /app-two/**