version: '3'
services:

  ms-one:
    image: donascimentomarcelo/ms-one:1.3
    ports:
      - 8001:8001
    depends_on:
      - eureka-server
    networks:
      - ms-kubernetes-net
    links:
      - eureka-server

  ms-two:
    image: donascimentomarcelo/ms-two:1.2
    ports:
      - 8002:8002
    depends_on:
      - eureka-server
    networks:
      - ms-kubernetes-net
    links:
      - eureka-server

  eureka-server:
    image: donascimentomarcelo/eureka-server-kube:1.0
    ports:
      - 8761:8761
    hostname: eureka-server
    networks:
      - ms-kubernetes-net

  hr-api-gateway-zuul:
    image: donascimentomarcelo/api-gateway-zuul-kube:1.1
    ports:
      - 8765:8765
    depends_on:
      - eureka-server
    networks:
      - ms-kubernetes-net
    links:
      - eureka-server

networks:
  ms-kubernetes-net:
    driver: bridge
